syntax = "proto3";
package admin;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "types.proto";

service ConsoleUserService {
  rpc GetLog (ListUsersRequest) returns (ConsoleUserListResponse);
  rpc GetLatest (ListUsersRequest) returns (ConsoleUserListResponse);
  rpc FindUsers (FindUsersRequest) returns (ConsoleUserListResponse);
  rpc GetVersions (GetUserVersionsRequest) returns (ConsoleUserListResponse);
  rpc ToggleBlocked (ToggleBlockedRequest) returns (google.protobuf.Empty);
  rpc SetQuota (SetQuotaRequest) returns (google.protobuf.Empty);
}

message ListUsersRequest {
  int32 limit = 1;
  optional bool is_blocked = 2;
}

message FindUsersRequest {
  string query = 1;                   // user id prefix or email substring
}

message GetUserVersionsRequest {
  string query = 1;                   // user id prefix or email substring
  int32 limit = 2;
}

message ConsoleUserResponse {
  common.EntityId id = 1;
  common.EntityId user_id = 2;
  string email = 3;
  string full_name = 4;
  int64 allowed_storage = 5;
  int64 taken_storage = 6;
  bool is_blocked = 10;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
  int32 version = 9;
}

message ConsoleUserListResponse {
  repeated ConsoleUserResponse users = 1;
}

message ToggleBlockedRequest {
  common.EntityId user_id = 1;
  bool is_blocked = 2;
}

message SetQuotaRequest {
  common.EntityId user_id = 1;
  int64 allowed_storage = 2;
}
