[package]
name = "pavuk-nas"
version = "0.1.0"
description = "My Homelab NAS Client"
authors = ["Leonid Romaniukha:@leora26"]
edition = "2021"


[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
tonic-build = "0.12"
protoc-bin-vendored = "3.2.0"


[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1", features = ["full"] }

tonic = "0.12"

prost = "0.13"

prost-types = "0.13"
chrono = "0.4"
tauri-plugin-shell = "2.3.5"
async-stream = "0.3.6"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-deep-link = "2.4.9"
url = "2.5.8"
webbrowser = "1.2.1"
tauri-plugin-single-instance = "2"
rand = "0.8.5"
sha2 = "0.10.8"
base64 = "0.22.1"
reqwest = { version = "0.12", features = ["json", "stream"] }
futures-util = "0.3"
uuid = { version = "1.20.0", features = ["v4"] }
