set shell := ["powershell.exe", "-c"]

migrate:
    sqlx migrate run

revert:
    sqlx migrate revert

reset:
    sqlx database reset -y

prepare:
    cd apps/nas-server; cargo sqlx prepare
    cd apps/user-management; cargo sqlx prepare
    cd apps/admin-console; cargo sqlx prepare

build:
    cargo build

ready: migrate prepare
    cargo fmt
    cargo test
    @echo "✅ Ready to push!"

populate:
    cargo run -p nas-server --bin seed