services:
  postgres:
    image: postgres:16-alpine
    container_name: pavuk_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pavuk
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pavuk_net

  # 🐰
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pavuk_mq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # Main communication port
      - "15672:15672" # Management Dashboard (Browser)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pavuk_net

  zitadel:
    image: ghcr.io/zitadel/zitadel:v4.14.0
    container_name: zitadel
    depends_on:
      - postgres
    command: start-from-init --masterkey "${ZITADEL_MASTERKEY}" --tlsMode disabled
    ports:
      - "8085:8080"
    environment:
      # --- Database Connection ---
      - ZITADEL_DATABASE_POSTGRES_HOST=postgres
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_SSL_MODE=disable

      # --- Database Admin Connection (For setup and migrations) ---
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      
      # --- Database Runtime Connection (For daily operations) ---
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DB_PASSWORD}

      # --- Server Configuration ---
      - ZITADEL_EXTERNALPORT=8085
      - ZITADEL_EXTERNALSECURE=false 
      
      # --- First Admin User ---
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=setup
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Setup
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=admin
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=${ZITADEL_ADMIN_PASSWORD}

      # --- Server Configuration ---
      - ZITADEL_EXTERNALDOMAIN=localhost
      - ZITADEL_EXTERNALPORT=8085
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED=false
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=setup
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Setup
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_PATH=/machinekeys/setup-key.json
    
    restart: unless-stopped
    networks:
      - pavuk_net
    volumes:
      - ./zitadel_keys:/machinekeys

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  pavuk_net:
    driver: bridge
